### ISSUE TITLE
Bug: "publish another one" copies contents for updates

### ISSUE THREAD

**Issue by Ostrzyciel** [knowledgepixels/nanodash#102]
To reproduce:
- Publish a nanopublication using some template.
- In nanodash, open the nanopub and from the dropdown select "update".
- Publish the updated nanopub.
- Now click on "publish another one with same template".

The result should be a clean form with the same template. Instead, the template is pre-filled with the content of the previous nanopub. I think this is because the `supersede` URL parameter is mistakenly carried over.

I would classify this as a "minor annoyance" – it's easy to walk around, but it may confuse users.

**Comment by tkuhn** [comment]
Yes, good point, thanks for reporting!

For other params, it makes sense at least in some situations for them to be carried over. But I agree that it doesn't make sense in this case and is confusing for users.

I am only thinking right now whether `supersede` is the only param that should be blocked. For `derive`, one could argue this to be a feature rather than a bug (if someone want to derive multiple nanopubs from a given one), and even more so for the `param_...` arguments to fill in certain parts of the form...

Maybe just filtering out `supersede` is a good first step.

Later, if we find a user-friendly way to present it, there could be two buttons, one for the plain template and one for the template with params applied (the latter disabled for `supersede`).

**Comment by Ostrzyciel** [comment]
Agreed! I think the approach with two buttons would be ideal :)

**Comment by tkuhn** [comment]
Fixed with 01cbe533d380a1aac41d0304f38ad12e9b7641a1. (not yet live)
